MYSQL-HOST: 127.0.0.1
MYSQL-PORT: 3306
MYSQL-USERNAME: dev
MYSQL-PASSWORD: dev
SERVER-PORT: 8081

server:
  port: ${SERVER-PORT}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL-PORT}/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ${MYSQL-USERNAME}
    password: ${MYSQL-PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 39.105.162.129:8848
        namespace: ${spring.profiles.active}

# 自定义参数
wpk:
  # nettyServer配置
  netty:
    name: netty-server
    port: 60000
    bossThreads: 1
    workerThreads: 4
    webSocketPath: "/ws"
    readerIdleTime: 60
    writerIdleTime: 60
    allIdleTime: 120

