server:
  port: 80
spring:
  profiles:
    active: dev
  application:
    name: cloud-gateway

logging:
  level:
    root: info
  # 日志配置文件
  config: classpath:log4j2-spring-${spring.profiles.active}.xml
